model_type: dit
run_name: 20251020
dataset_type: basic

data_manager:
  experiments:
    ops0033_20250429:
      - A/1/0
      - A/2/0
      - A/3/0
  batch_size: 16
  data_split: 
    - 0.95
    - 0.025
    - 0.025
  out_channels:
    - mCherry
  initial_yx_patch_size:
    - 256
    - 256
  num_workers: 8

callbacks:
  monitor: "val/loss"

trainer:
  max_epochs: 200
  limit_train_batches: 3000
  limit_val_batches: 400

dit_kwargs:
  input_size: 16
  patch_size: 2
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  class_dropout_prob: 0.1
  num_classes: 1000
  learn_sigma: True

vae_kwargs:
  model_checkpoint: /hpc/projects/intracellular_dashboard/ops/models/model_checkpoints/diffusers_ae/20250930-2025-09-30-val/loss=0.00.ckpt
  in_channels: 1
  out_channels: 1
  block_out_channels:
    - 64
    - 128
    - 256
    - 256
  latent_channels: 4
  down_block_types: 
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
  up_block_types:
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
  layers_per_block: 1
  act_fn: silu
  norm_num_groups: 32
  sample_size: 32
  scaling_factor: 0.18215
  shift_factor: None
  latents_mean: None
  latents_std: None
  force_upcast: True
  use_quant_conv: True
  use_post_quant_conv: True
  mid_block_add_attention: False

vae_lightning_config:
  gen_lr: 0.00001
  disc_lr: 0.0000045
  kl_weight: 1.0
  disc_factor: 1.0
  disc_iter_start: 20001
  discriminator_weight: 0.5
