model_type: diffusers_ae
run_name: 20250930
dataset_type: basic

data_manager:
  experiments:
    ops0033_20250429:
      - A/1/0
      - A/2/0
      - A/3/0
  batch_size: 64
  data_split: 
    - 0.95
    - 0.025
    - 0.025
  out_channels:
    - GFP
  initial_yx_patch_size:
    - 256
    - 256
  num_workers: 8

model:
  in_channels: 1
  out_channels: 1
  block_out_channels:
    - 64
    - 128
    - 256
    - 256
  latent_channels: 4
  down_block_types: 
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
  up_block_types:
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
  layers_per_block: 1
  act_fn: silu
  norm_num_groups: 32
  sample_size: 32
  scaling_factor: 0.18215
  shift_factor: None
  latents_mean: None
  latents_std: None
  force_upcast: True
  use_quant_conv: True
  use_post_quant_conv: True
  mid_block_add_attention: False

lightning_config:
  gen_lr: 0.00001
  disc_lr: 0.0000045
  kl_weight: 1.0
  disc_factor: 1.0
  disc_iter_start: 20001
  discriminator_weight: 0.5

trainer:
  max_epochs: 200
  limit_train_batches: 3000
  limit_val_batches: 400

callbacks:
  monitor: "val/loss"
