"""Run all three SHAP-contrast atlases in one command.

For a given --aggregation-level, fires `attention_atlas_shap.py` 3 times:
    distinct  → attention_distinct_{geneKO,chad}/atlas_distinct.pdf
    ntc       → attention_ntc_{geneKO,chad}/atlas_ntc.pdf
    global    → attention_global_{geneKO,chad}/atlas_global.pdf

Each contrast reads its own SHAP CSV (generated by
`run_shap_pipeline.py --distinct-contrast {distinct,ntc,global}`); the
violin BG sample is sourced from the SHARED `bg_refs/` cache
(`all_cells_v2/<channel>.h5ad` sampled ONCE per contrast and reused
across atlases).

Usage:
  # All 3 CHAD-level atlases (assumes the 3 SHAP CSVs exist)
  python organelle_profiler/scripts/ko_shap/run_all_atlases.py \
      --aggregation-level complex

  # Only specific contrasts (skip distinct if already rendered)
  python organelle_profiler/scripts/ko_shap/run_all_atlases.py \
      --aggregation-level complex --contrasts ntc global

  # Local smoke for a single complex across all 3 contrasts
  python organelle_profiler/scripts/ko_shap/run_all_atlases.py \
      --aggregation-level complex --local --genes "subu Augmin" \
      --extra-atlas-args --no-strict --no-ntc
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
ATLAS = REPO / "ops_process" / "ops_analysis" / "napari" / "attention_atlas_shap.py"
ALEX_BASE = Path("/hpc/projects/icd.fast.ops/models/alex_lin_attention")

# Per-(variant, contrast, aggregation) → output paths. Output dir
# naming follows the {variant}_{contrast}_{grain} scheme — same
# layout used by run_shap_pipeline.py so atlases land next to their
# SHAP CSVs without manual path-juggling.
def _paths(variant: str, contrast: str, level: str) -> dict:
    grain = "chad" if level == "complex" else "geneKO"
    if variant == "top-attention":
        out_root = ALEX_BASE / f"attention_{contrast}_{grain}"
        # Top-attention positives are identical across all 3 contrasts at
        # a given grain (top-attention cells); only negatives differ →
        # same SHAP cache.
        cache_root = ALEX_BASE / "shap_caches" / ("v4_chad" if level == "complex" else "v4")
        return {
            "out_dir":           out_root,
            "shap_features_csv": out_root / "ko_shap_features.csv",
            "shap_captions_csv": out_root / "ko_shap_captions.csv",
            "shap_cache_phase":  cache_root / "phase",
            "shap_cache_fluor":  cache_root / "fluor",
            # No picker outputs — top-attention reuses pma_top_* CSVs
            # at the atlas's default arg values.
            "picker_phase_csv":  None,
            "picker_fluor_csv":  None,
        }
    # all-cells variant
    out_root = ALEX_BASE / f"all_cells_{contrast}_{grain}"
    cache_root = ALEX_BASE / "ntc_caches" / ("v2_chad" if level == "complex" else "v2")
    return {
        "out_dir":           out_root,
        # ntc_shap_features.py writes one features file + per-contrast
        # captions under the all_cells_<contrast>_<grain>/ dir.
        "shap_features_csv": out_root / "all_cells_shap_features.csv",
        "shap_captions_csv": out_root / f"all_cells_shap_captions_{contrast}.csv",
        # NTC fluor cache is a parent dir of per-channel subdirs; phase
        # is a single subdir.
        "shap_cache_phase":  cache_root / "phase",
        "shap_cache_fluor":  cache_root,
        # Step-4 picker outputs (KO + KO-typical-NTC rows in one CSV).
        "picker_phase_csv":  out_root / f"picked_phase_{contrast}.csv",
        "picker_fluor_csv":  out_root / f"picked_fluor_{contrast}.csv",
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--variant", choices=("top-attention", "all-cells"),
                     default="top-attention",
                     help="Which SHAP source to render. `top-attention` "
                          "(default) reads from attention_<contrast>_<grain>/; "
                          "`all-cells` reads from all_cells_<contrast>_<grain>/ "
                          "and forwards the step-4 picker outputs as "
                          "image-row CSVs.")
    ap.add_argument("--aggregation-level", choices=("gene", "complex"),
                     default="complex")
    ap.add_argument("--contrasts", nargs="+",
                     default=["distinct", "ntc", "global"],
                     choices=("distinct", "ntc", "global"))
    ap.add_argument("--genes", nargs="+", default=None,
                     help="Optional gene/complex filter passed to the atlas")
    ap.add_argument("--local", action="store_true",
                     help="Use --local on each atlas run instead of SLURM")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument(
        "--output-dir", type=Path, default=None,
        help="Override the output directory. When --genes is set "
             "(smoke mode), defaults to /hpc/mydata/<user>/smoke_atlases/ "
             "so the full-atlas PDFs in top20_v4_chad{,_ntc,_global} "
             "aren't clobbered. When --genes is empty (full atlas run), "
             "defaults to the per-contrast top20_v4_* directory.",
    )
    ap.add_argument("--extra-atlas-args", nargs=argparse.REMAINDER,
                     default=[],
                     help="Anything after this is forwarded verbatim to "
                          "every atlas invocation (e.g. --no-strict --skip-cp-4i).")
    args = ap.parse_args()

    # Smoke mode (--genes set) routes outputs to a separate directory so
    # the canonical full-atlas PDFs in top20_v4_chad{,_ntc,_global}/
    # don't get overwritten by a 1-gene smoke render.
    is_smoke = bool(args.genes)
    default_smoke_dir = Path("/hpc/mydata") / os.environ.get("USER", "gav.sturm") / "smoke_atlases"
    out_dir_override = args.output_dir or (default_smoke_dir if is_smoke else None)
    if is_smoke:
        out_dir_override.mkdir(parents=True, exist_ok=True)

    # Detect variable-page-size mode from --extra-atlas-args so the
    # output filename reflects which layout was used. Without this tag
    # a `--map-channel-threshold X > 0` run would overwrite the
    # fixed-3 baseline PDF in the same out_dir.
    extra = list(args.extra_atlas_args or [])
    variable_tag = ""
    for i, tok in enumerate(extra):
        if tok == "--map-channel-threshold" and i + 1 < len(extra):
            try:
                if float(extra[i + 1]) > 0:
                    variable_tag = "_variable"
            except ValueError:
                pass
            break

    for contrast in args.contrasts:
        p = _paths(args.variant, contrast, args.aggregation_level)
        suffix = "_smoke" if is_smoke else ""
        # Filename also reflects variant — top-attention pages and
        # all-cells pages can land in adjacent dirs without collision.
        variant_tag = "" if args.variant == "top-attention" else "_all_cells"
        out_dir = out_dir_override or p["out_dir"]
        out_pdf = out_dir / f"atlas_{contrast}{variant_tag}{suffix}{variable_tag}.pdf"
        cmd = [
            sys.executable, str(ATLAS),
            "--aggregation-level", args.aggregation_level,
            "--contrast", contrast,
            "--shap-features-csv", str(p["shap_features_csv"]),
            "--shap-captions-csv", str(p["shap_captions_csv"]),
            "--shap-cache-phase",  str(p["shap_cache_phase"]),
            "--shap-cache-fluor",  str(p["shap_cache_fluor"]),
            "--output", str(out_pdf),
        ]
        # all-cells: forward picker outputs as image-row CSVs. The
        # same CSV serves both the KO row (--phase-csv / --fluor-csv,
        # filtered to rank_type==top) and the NTC strip pool
        # (--ntc-pma-*-csv, filtered to rank_type==ntc_ko_typical +
        # target_gene). See ntc_pick_cells.py for schema.
        if p["picker_phase_csv"] is not None:
            missing = (
                not p["picker_phase_csv"].exists()
                or not p["picker_fluor_csv"].exists()
            )
            if missing and not args.dry_run:
                raise FileNotFoundError(
                    f"All-cells picker outputs missing for contrast={contrast}: "
                    f"{p['picker_phase_csv']} / {p['picker_fluor_csv']}. "
                    f"Run `run_shap_pipeline.py --variant all-cells "
                    f"--contrast {contrast} --aggregation-level "
                    f"{args.aggregation_level} --from-step 4 --smoke-genes 0` "
                    f"first."
                )
            if missing:
                print(f"  [dry-run] picker outputs MISSING for {contrast} — "
                      f"would need step 4 of run_shap_pipeline.py first.")
            cmd += [
                "--phase-csv",         str(p["picker_phase_csv"]),
                "--fluor-csv",         str(p["picker_fluor_csv"]),
                "--ntc-pma-phase-csv", str(p["picker_phase_csv"]),
                "--ntc-pma-fluor-csv", str(p["picker_fluor_csv"]),
            ]
        if args.local:
            cmd.append("--local")
        if args.genes:
            cmd += ["--genes", *args.genes]
        cmd += list(args.extra_atlas_args)
        print("\n" + "=" * 72)
        print(f"[contrast={contrast}] {' '.join(cmd)}")
        print("=" * 72, flush=True)
        if args.dry_run:
            continue
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
